def how_to_play() -> str:
    """Player-facing orientation text: what kind of game this is, how the Sitting works, and when to call an Omen."""
    return (
        "\"Until you make the unconscious conscious, it will direct your life and "
        "you will call it fate.\" — C.G. Jung\n"
        "\n"
        "Welcome to the Fortuneteller's Hand. Here you take your imagination for a "
        "walk into the realm of fate and back. The cards will speak first — but "
        "only you can take what they surface and give it a shape, a meaning, a way "
        "forward for your character's Goal.\n"
        "\n"
        "To know who you are, you first sit with the Fortuneteller. You'll be asked "
        "what they look like, and where you meet them — the first choice made, "
        "before any card is drawn.\n"
        "\n"
        "Then you turn inward. Four suits, four facets of who you are: Hearts is "
        "love, loyalty, bonds. Diamonds is wealth, desire, ambition. Clubs is labor, "
        "craft, growth. Spades is death, conflict, endings. You decide which suit "
        "answers which facet — Motivation, Ends, Seek, and Carry — the one true "
        "choice you make about your own fate. Once all four are assigned, the "
        "Fortuneteller draws one card blind from each, speaking what it reveals. "
        "From those four cards, you build your character: their history, their "
        "psychology, who they are before the story begins.\n"
        "\n"
        "Once your character exists, the Fortuneteller deals one more card: your "
        "Goal. Interpret it the way you interpreted the rest — how does it relate to "
        "who you are, and where might it take you?\n"
        "\n"
        "Each card carries a phrase — read it the way a fortuneteller would, but "
        "truer: not just what it says, but how it lands in this exact scene. Let it "
        "shape your narration, decide where the scene goes next, and who it brings "
        "into it. Every scene works the same way: decide where you are, flip a new "
        "card to see what's stirring, then narrate forward — where you are, what you "
        "feel, what you see, what your character is doing. The moment you reach "
        "another heart, something hidden, or need a turn of luck, call an Omen.\n"
        "\n"
        "An Omen is how you ask fate directly, instead of deciding something that "
        "was never yours to decide. A scene closes once the Omen has been called "
        "and answered, and what the flipped card set in motion has been fulfilled "
        "in the story — then a new scene begins."
    )
